name: genecards CI

on: [push]

jobs:

  genecards:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: pip install scrapy pandas
    - run: scrapy crawl genecards -o result.csv
    - uses: actions/upload-artifact@v1
      with:
        name: genecards
        path: result.csv
